services:
  - type: web
    name: umami
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: athanor_umami_db
          property: connectionString
      - key: DATABASE_TYPE
        value: postgresql
      - key: APP_SECRET
        generateValue: true
